### ISSUE TITLE
no match for ‘operator<’

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#546]
I have a class

```
class Item
{

public:
    Item() {}

    int getId() const
    {
        return mId;
    }
    void setId(int id)
    {
        mId = id;
    }
    std::string getString() const
    {
        return mString;
    }
    void setString(std::string str)
    {
        mString = str;
    }
    
private:
    int mId;
    std::string mString;
};
```

now I want to quey but a compilation error has occurred.

```
sqlite_orm::where(sqlite_orm::c(&Item::getId) < 10)
```

The error message is 

```
error: no match for ‘operator<’ (operand types are ‘sqlite_orm::internal::expression_t<int (Item::*)() const>’ and ‘int’)
[build]                                                                                                         sqlite_orm::c(&Item::getId) < 10
```

How can I resolve it?

**Comment by fnc12** [comment]
```c++
class Item
    {

    public:
        Item() {}

        int getId() const
        {
            return mId;
        }
        void setId(int id)
        {
            mId = id;
        }
        std::string getString() const
        {
            return mString;
        }
        void setString(std::string str)
        {
            mString = str;
        }
        
    private:
        int mId;
        std::string mString;
    };
    auto storage = make_storage({},
                                make_table("users",
                                           make_column("id", &Item::getId, &Item::setId),
                                           make_column("string", &Item::getString, &Item::setString)));
    storage.sync_schema();
    storage.get_all<Item>(sqlite_orm::where(sqlite_orm::c(&Item::getId) < 10));
```
this code compiles well on `dev` branch. What branch do you use?

**Comment by HyperionChen** [comment]
release v1.4

**Comment by fnc12** [comment]
@HyperionChen try `dev` cause this issue was already fixed before

**Comment by HyperionChen** [comment]
> @HyperionChen try `dev` cause this issue was already fixed before


I copy the sqlite_orm.h from dev branch. But the compile error still exist.

It's ok by this way

```
std::vector<Item> lsts = storage.get_all<Item>(sqlite_orm::where(sqlite_orm::lt(&Item::getId, 10)));
```

but why doesn't it match **operator==**?

**Comment by fnc12** [comment]
Oh I got it. You miss `using` directive. Either add `using namespace sqlite_orm` or `using sqlite_orm::operator<`

**Comment by HyperionChen** [comment]
add **using namespace sqlite_orm** is effective.

but the query result is strange. The primaryKey id sometime is -702300088，sometime is 29433040. I open the db file with sqlite3 command, the id is between 1 and 100.

**Comment by HyperionChen** [comment]
Oh How stupid I was. I forgot to initialize the id in the constructor. Thank you.

**Comment by fnc12** [comment]
is the issue actual?

**Comment by HyperionChen** [comment]
It's works.
