### ISSUE TITLE
Can't build from source, fail to fetch Catch2

### ISSUE THREAD

**Issue by fmichaut-epitech** [fnc12/sqlite_orm#648]
I tried to follow the install instructions in the readme :
```git clone https://github.com/fnc12/sqlite_orm.git sqlite_orm
cd sqlite_orm
cmake -B build
cmake --build build --target install
```

But I encountered an issue during the execution of theses steps.
The Catch2 dependecy fail with the folowing message : 
```-- SQLITE_ORM: Build with C++14 features
-- Configuring sqlite_orm 1.3.0
[ 11%] Performing download step (git clone) for 'catch2-populate'
Cloning into 'catch2-src'...
fatal: invalid reference: master
CMake Error at catch2-subbuild/catch2-populate-prefix/tmp/catch2-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'


gmake[2]: *** [CMakeFiles/catch2-populate.dir/build.make:112: catch2-populate-prefix/src/catch2-populate-stamp/catch2-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/catch2-populate.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2

CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:912 (message):
  Build step for catch2 failed: 2
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:1003 (__FetchContent_directPopulate)
  /usr/share/cmake/Modules/FetchContent.cmake:1044 (FetchContent_Populate)
  dependencies/catch2/CMakeLists.txt:1 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
See also "/tmp/sqlite_orm/build/CMakeFiles/CMakeOutput.log".
gmake: *** No rule to make target 'install'.  Stop.
```

It looks like the ref "master" doesn't exist anymore in the Catch2 github repository. I cloned it to verify, and indeed the master branch wasn't there. The default branch when cloning the repository is now "devel".
I guess it's more a CMake issue, looking for a default "master" branch in the repository. 

But as a workaround, I was able to pass this step by editing the content of the `dependencies/CMakeLists.txt` and added `GIT_TAG devel` in the FetchContent declaration. 

I think this workaround should be included in sqlite_orm until CMake fixes it

**Comment by fnc12** [comment]
hi @fmichaut-epitech . Yes the problem exists and it is fixed in `dev` branch. Catch2 was attacked by social justice warriors and removed `master` branch probably cause `master` makes someone feel uncomfortable or something like this. It is very unpleasant case at all. It would be great if you'll fix it in `master` branch in this repo cause `master` is failing right now.
BTW you use `sqlite_orm` 1.3. It is an old version. The latest version is 1.6.
P.S. This repo will remain `master` branch and no matter what some SJW think about it.

**Comment by fmichaut-epitech** [comment]
Okay, well even if I change this in the main branch, I think the build will still not succed.
I had another error when I tried to build the project on the master branch : 

```
[ 47%] Building CXX object tests/CMakeFiles/unit_tests.dir/tests.cpp.o
cd /tmp/sqlite_orm/build/tests && /usr/lib64/ccache/c++   -I/tmp/sqlite_orm/include -I/tmp/sqlite_orm/build/_deps/catch2-src/src/catch2/..  -std=c++14 -o CMakeFiles/unit_tests.dir/tests.cpp.o -c /tmp/sqlite_orm/tests/tests.cpp
/tmp/sqlite_orm/tests/tests.cpp:5:10: fatal error: catch2/catch.hpp: No such file or directory
    5 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [tests/CMakeFiles/unit_tests.dir/build.make:86: tests/CMakeFiles/unit_tests.dir/tests.cpp.o] Error 1
gmake[2]: Leaving directory '/tmp/sqlite_orm/build'
gmake[1]: *** [CMakeFiles/Makefile2:1094: tests/CMakeFiles/unit_tests.dir/all] Error 2
gmake[1]: Leaving directory '/tmp/sqlite_orm/build'
gmake: *** [Makefile:164: all] Error 2
```
I tried to find "catch.hpp" in the repo, the only location `find` returned was `./third_party/vcpkg/toolsrc/include/catch2/catch.hpp`
(I tried to exec "./build.sh" at the begining, that downloaded this file if i'm not mistaken).
So I don't know what we should do to fix this issue, maybe on `dev` you have a real solution for this error ?

I just used `cp -r /tmp/sqlite_orm/third_party/vcpkg/toolsrc/include/catch2 /tmp/sqlite_orm/include` since  the Makefile had `-I/tmp/sqlite_orm/include` as an include path and I just wanted to build the project fast, so I didn't looked for a "real" fix for this issue

How should we fix it ?

**Comment by fnc12** [comment]
Everything must work in `dev` branch. At least it works on CI (travis and appveyor) for sure. I don't use cmake for myself then this is all I can tell. If error still exists in `dev` I'd like you to fix this. Thanks in advance

**Comment by fmichaut-epitech** [comment]
Okay, do I checked on the `dev` branch, and it was indeed working.

The issue that I've been facing was because I checked out the branch `devel` of catch2, in which (for whatever reason) the directory `include` doesn't exists anymore.

So just by adding `GIT_TAG v2.13.2` in `dependencies/CMakeLists.txt` on `master`, the issue should be solved
I created a pull request with just that change targeting master : #650
